//! S1 IPC contract codegen (ADR-0016). Rust is the single source of truth;
//! `cargo test` regenerates the TypeScript counterparts into `src/lib/ipc/`
//! plus an `events.ts` event-name map and an `index.ts` barrel. A clean tree
//! after running this means no drift; CI fails the build on any diff
//! (`git diff --exit-code`, wired in R2).

use std::fs;
use std::path::PathBuf;

use ts_rs::{Config, TS};

use ruckel_lib::encoder::{
    events, CancelledEvent, ConversionError, DoneEvent, FileDoneEvent, FileErrorEvent,
    ProgressEvent,
};
use ruckel_lib::preflight::collision::Collision;
use ruckel_lib::preflight::plan::{
    Audio, ConversionJob, ConversionOptions, Framerate, Resolution,
};
use ruckel_lib::preflight::PreflightResult;
use ruckel_lib::preflight::FileProbe;

/// Repo-root `src/lib/ipc/` (the test runs from `src-tauri/`).
fn ipc_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/lib/ipc")
}

#[test]
fn generate_ipc_bindings() {
    let dir = ipc_dir();
    fs::create_dir_all(&dir).expect("create src/lib/ipc");

    // ts-rs 12 default config: extensionless imports, `number` for the small
    // integer/float types this contract uses (no `bigint`).
    let cfg = Config::new();

    // One `.ts` per contract type, generated by ts-rs (imports resolve to
    // sibling files in this same directory). Order here does not matter — the
    // barrel below is sorted for determinism.
    let mut type_names: Vec<String> = Vec::new();
    macro_rules! emit_types {
        ($($t:ty),+ $(,)?) => {{
            $(
                let content = <$t as TS>::export_to_string(&cfg)
                    .expect(concat!("export ", stringify!($t)));
                let name = <$t as TS>::ident(&cfg);
                fs::write(dir.join(format!("{name}.ts")), content)
                    .expect("write type binding");
                type_names.push(name);
            )+
        }};
    }
    emit_types!(
        Resolution,
        Framerate,
        Audio,
        ConversionOptions,
        ConversionJob,
        Collision,
        PreflightResult,
        FileProbe,
        ProgressEvent,
        FileDoneEvent,
        FileErrorEvent,
        ConversionError,
        DoneEvent,
        CancelledEvent,
    );

    fs::write(dir.join("events.ts"), render_events()).expect("write events.ts");

    type_names.sort();
    fs::write(dir.join("index.ts"), render_index(&type_names)).expect("write index.ts");
}

/// The `events.ts` constant map, built from the Rust source of truth
/// (`encoder::events::ALL`) so the event strings are never hand-duplicated.
fn render_events() -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("// Source of truth: src-tauri/src/encoder/mod.rs (`events`).\n\n");
    out.push_str("export const CONVERSION_EVENTS = {\n");
    for (name, value) in events::ALL {
        out.push_str(&format!("  {name}: '{value}',\n"));
    }
    out.push_str("} as const\n\n");
    out.push_str("export type ConversionEventName =\n");
    out.push_str("  (typeof CONVERSION_EVENTS)[keyof typeof CONVERSION_EVENTS]\n");
    out
}

/// The `index.ts` barrel re-exporting every generated type plus the event map.
fn render_index(type_names: &[String]) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    for name in type_names {
        out.push_str(&format!("export type {{ {name} }} from './{name}'\n"));
    }
    out.push('\n');
    out.push_str("export { CONVERSION_EVENTS } from './events'\n");
    out.push_str("export type { ConversionEventName } from './events'\n");
    out
}

const GENERATED_HEADER: &str = "\
// This file was generated by the Ruckel S1 IPC codegen (`cargo test`).
// Do not edit by hand — change the Rust contract types and regenerate.
";
