// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio knob (ADR-0007). `None` maps to `-an` (no audio); the bitrates map to
 * `-b:a`. A bitrate on a source without audio is a no-op.
 */
export type Audio = "Kbps192" | "Kbps128" | "Kbps96" | "None";
