// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `conversion:cancelled` — the batch was cancelled; the in-flight temp file
 * has been cleaned up (ADR-0012, ADR-0013). Carries no data.
 */
export type CancelledEvent = Record<symbol, never>;
