// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A planned `_ppt` output path that already exists on disk (ADR-0014).
 * Detected in pre-flight and surfaced in the `PreflightResult` so the
 * frontend can prompt for a resolution before any encode runs.
 */
export type Collision = { 
/**
 * Index into the plan's job list this collision belongs to.
 */
job_index: number, source_path: string, 
/**
 * The existing `_ppt` output path that would be overwritten.
 */
output_path: string, };
