// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Audio } from "./Audio";
import type { Framerate } from "./Framerate";
import type { Resolution } from "./Resolution";

/**
 * The four user-facing encode knobs (ADR-0007). CRF is the raw 18–28 value
 * (the UI surfaces 18/23/28; an Advanced stepper is deferred). The
 * PowerPoint-safe flags (ADR-0006) are fixed and not represented here.
 */
export type ConversionOptions = { resolution: Resolution, crf: number, framerate: Framerate, audio: Audio, };
