// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One failure in the end-of-batch summary (ADR-0015).
 */
export type ConversionError = { file_name: string, error_message: string, };
