// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionOptions } from "./ConversionOptions";

/**
 * One resolved unit of work (ADR-0010): a source path, its planned `_ppt`
 * output path (ADR-0008), and the four options applied.
 */
export type ConversionJob = { source_path: string, output_path: string, options: ConversionOptions, };
