// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionError } from "./ConversionError";

/**
 * `conversion:done` — the batch finished; carries the skip-and-continue
 * summary (ADR-0015): how many succeeded, how many failed, and every reason.
 */
export type DoneEvent = { succeeded: number, failed: number, errors: Array<ConversionError>, };
