// This file was generated by the Ruckel S1 IPC codegen (`cargo test`).
// Do not edit by hand — change the Rust contract types and regenerate.
// Source of truth: src-tauri/src/encoder/mod.rs (`events`).

export const CONVERSION_EVENTS = {
  PROGRESS: 'conversion:progress',
  FILE_DONE: 'conversion:file_done',
  FILE_ERROR: 'conversion:file_error',
  DONE: 'conversion:done',
  CANCELLED: 'conversion:cancelled',
} as const

export type ConversionEventName =
  (typeof CONVERSION_EVENTS)[keyof typeof CONVERSION_EVENTS]
