// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `conversion:file_done` — one job finished; `<stem>_ppt.mp4` now exists.
 */
export type FileDoneEvent = { file_index: number, output_path: string, };
