// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `conversion:file_cancelled` — one job was cancelled individually (ADR-0025);
 * the batch continues. Any in-flight temp file has been cleaned up (ADR-0012).
 * Distinct from `conversion:cancelled`, which aborts the whole batch.
 */
export type FileCancelledEvent = { file_index: number, };
