// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `conversion:file_error` — one job failed; the batch continues (ADR-0015).
 */
export type FileErrorEvent = { file_index: number, file_name: string, error_message: string, };
