// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-file probe metadata surfaced in the pre-flight result (ADR-0020, S1
 * amendment). 1:1 with `plan` by position — the frontend iterates both
 * together. Kept separate from `ConversionJob` so the encoder input stays
 * clean (the encoder re-probes duration and only needs the job fields).
 *
 * `size_bytes` is the source file's on-disk size — filesystem metadata, not a
 * probe field — carried here so the frontend's phased reveal (ADR-0020) can
 * show size from the first frame without a separate IPC round-trip. It is an
 * `f64` (not `u64`) so the generated TS stays a plain `number`; exact for any
 * real video size.
 */
export type FileProbe = { duration_secs: number, width: number, height: number, size_bytes: number, };
