// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-file probe metadata surfaced in the pre-flight result (ADR-0020, S1
 * amendment). 1:1 with `plan` by position — the frontend iterates both
 * together. Kept separate from `ConversionJob` so the encoder input stays
 * clean (the encoder re-probes duration and only needs the job fields).
 */
export type FileProbe = { duration_secs: number, width: number, height: number, };
