// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Framerate cap (ADR-0007). `Original` leaves the source rate untouched.
 */
export type Framerate = "Original" | "Fps60" | "Fps30" | "Fps24";
