// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionJob } from "./ConversionJob";
import type { FileProbe } from "./FileProbe";

/**
 * The output of pre-flight (ADR-0010, ADR-0016): the fully-resolved plan and
 * per-file probe metadata (duration + resolution for the frontend's phased
 * reveal, ADR-0020). Part of the frozen IPC contract (S1).
 *
 * Collision detection no longer lives here (ADR-0025): whether a planned output
 * already exists is checked fresh at convert time via `check_collisions`, not
 * cached at drop time where it goes stale the instant the batch writes outputs.
 */
export type PreflightResult = { plan: Array<ConversionJob>, files: Array<FileProbe>, };
