// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Collision } from "./Collision";
import type { ConversionJob } from "./ConversionJob";
import type { FileProbe } from "./FileProbe";

/**
 * The output of pre-flight (ADR-0010, ADR-0016): the fully-resolved plan,
 * per-file probe metadata (duration + resolution for the frontend's phased
 * reveal, ADR-0020), and any output-path collisions the frontend must resolve
 * before encoding. Part of the frozen IPC contract (S1).
 */
export type PreflightResult = { plan: Array<ConversionJob>, files: Array<FileProbe>, collisions: Array<Collision>, };
