// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `conversion:progress` — live per-file progress at ~2 Hz (ADR-0013). Percent
 * is `out_time ÷ probed duration`, so it is accurate from the first frame.
 */
export type ProgressEvent = { file_index: number, total_files: number, file_name: string, percent: number, fps: number, speed: number, };
