// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resolution knob (ADR-0007). `Original` passes the source size through; the
 * rest cap the frame, aspect-preserving. The encoder maps these to a `scale`
 * filter (B2) — never a hardcoded `-level` (ADR-0006).
 */
export type Resolution = "Original" | "P1080" | "P720" | "P480";
